server:
  timeout: 10
  port: "8082"

apiMap:
  GetApplications:
    url: "get/applications"
    method: "GET"
  AcceptApplication:
    url: "update/app/admin"
    method: "PUT"
  CancelApplication:
    url: "cancel/app/admin"
    method: "POST"
  GetPrazdnik:
    url: "get/holiday"
    method: "GET"
  SaveHoliday:
    url: "save/holiday"
    method: "POST"
  GetVidiPrazdnikov:
    url: "get/vidi/prazdnikov"
    method: "GET"
  GetUslugi:
    url: "get/dop-uslugi"
    method: "GET"
  GetStatusiZakazchikov:
    url: "get/statusi-zakazchikov"
    method: "GET"
  SaveApplication:
    url: "save/application"
    method: "POST"
  GetCustomerApplications:
    url: "get/customer/applications"
    method: "GET"


db:
  host_db: "localhost"
  port_db: "5432"
  user: "application_service"
  password: "application_123"
  dbname: "organizaciya_meropriyatiy"
  sslmode: "disable"
