server:
  timeout: 10
  port: "8082"

apiMap:
  GetApplications:
    url: "get/applications"
    method: "GET"
  AcceptApplication:
    url: "update/app/admin"
    method: "PUT"
  CancelApplication:
    url: "cancel/app/admin"
    method: "POST"
  GetPrazdnik:
    url: "get/holiday"
    method: "GET"
  SaveHoliday:
    url: "save/holiday"
    method: "POST"

db:
  host_db: "localhost"
  port_db: "5432"
  user: "application_service"
  password: "application_123"
  dbname: "organizaciya_meropriyatiy"
  sslmode: "disable"
