server:
  timeout: 10
  port: "8081"

apiMap:
  AuthAdmin:
    url: "auth/admin"
    method: "POST"
  AuthAdminByToken:
    url: "auth/admin/token"
    method: "POST"
  GetAdminIdByToken:
    url: "get/admin/id"
    method: "POST"

  AuthRukovodstvo:
    url: "auth/ruk"
    method: "POST"
  AuthRukByToken:
    url: "auth/ruk/token"
    method: "POST"

db:
  host_db: "localhost"
  port_db: "5432"
  user: "auth_service"
  password: "auth_123"
  dbname: "organizaciya_meropriyatiy"
  sslmode: "disable"