server:
  timeout: 10
  port: "8081"

apiMap:
  AuthAdmin:
    url: "auth/admin"
    method: "POST"
  AuthAdminByToken:
    url: "auth/admin/token"
    method: "POST"
  GetAdminIdByToken:
    url: "get/admin/id"
    method: "POST"

db:
  host_db: "localhost"
  port_db: "5432"
  user: "postgres"
  password: "23032004tepor"
  dbname: "organizaciya_meropriyatiy"
  sslmode: "disable"