server:
  timeout: 10
  port: "8080"

handlers:
  LoginPage:
    url: "login"
    method: "GET"
  HomePage:
    url: ""
    method: "GET"
  TasksPage:
    url: "tasks"
    method: "GET"

api:
  Auth:
    url: "api/auth/admin"
    method: "POST"
  GetApplications:
    url: "api/applications"
    method: "GET"
  AcceptApplication:
    url: "api/application/accept"
    method: "POST"
  CancelApplication:
    url: "api/application/cancel"
    method: "POST"

accessExceptions:
  list:
    - ""
    - "tasks"
    - "api/applications"
    - "api/applications/accept"
    - "api/application/cancel"
